baseURL: https://blog.waringhu.com/
languageCode: zh-cn
title: "waringhu's blooog"
theme: zozo

# 首页显示文章数量
paginate: 4

authoe:
  name: "waringhu"

# 显示的文章摘要长度（单位未知）
summaryLength: 1

# 是否禁止将网站路径转换成小写
disablePathToLower: true

# 生成的文章的路径
permalinks:
  posts: "/posts/:year:month:day/:slug/"

menu:
  main:
    - name: "Home"
      weight: 10
      url: "/"
    - name: "Archive"
      weight: 20
      url: "/posts/"
    - name: "About"
      weight: 30
      url: "/about/"

params:
  subTitle: ":-)"
  footerSlogan: ":-)"
  keywords:
    - waringhu
    - blog
    - 产品设计
  description: "这是网站描述。"
  # 是否启用 MathJax
  enableMathJax: true
  # 是否显示文章摘要
  enableSummary: true
  mainSections:
    - posts
    - post
  valine:
    enable: false
    appId: ETRRV1wgYc8qfp4mfO4lGqCM-gzGzoHsz
    appKey: 4MNV8kPxKZDaZgzOVzkRQBp0
    placeholder: ""

social:
  # icon 来源：https://remixicon.com/
  github: "https://github.com/waringhu/" 
  mail: "mailto:waringhu@163.com"